In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,6])
print(arr)

[1 2 3 4 5 6]


In [3]:
arr2 = arr + 2
print(arr2)

[3 4 5 6 7 8]


In [4]:
arr3 = np.reshape(arr2, (3, 2))
print(arr3)


[[3 4]
 [5 6]
 [7 8]]


In [6]:
import numpy as np

def matrix_sum(N):
    matrix = np.random.randint(1, 10, size=(N, 3))
    row_sums = np.sum(matrix, axis=1)
    column_sums = np.sum(matrix, axis=0)
    return matrix, row_sums, column_sums

# Test the matrix_sum function
size = int(input("Enter the size of the matrix: "))
matrix, row_sums, column_sums = matrix_sum(size)

print("Matrix:")
print(matrix)
print("Sum of each row:")
print(row_sums)
print("Sum of each column:")
print(column_sums)

Matrix:
[[4 3 1]
 [4 1 5]
 [1 3 4]
 [8 1 9]]
Sum of each row:
[ 8 10  8 18]
Sum of each column:
[17  8 19]


In [1]:
arr = np.array([1,2,3,4,5])
print(arr.shape)
print(np.arange(61))
print(arr.ndim)


arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
sort = np.sort(arr)
print(sort)
print(sort.reshape(7,1))



arrange = np.arange(1,10,2)
print(arrange)


arr = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]])
print()
print(arr[0, 0:2, 1:4])

NameError: name 'np' is not defined

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

# view
print('view')
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

[42  2  3  4  5]
[1 2 3 4 5]
view
[42  2  3  4  5]
[42  2  3  4  5]
None
[1 2 3 4 5]


In [26]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)
print(newarr.base)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]


In [9]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# for x in np.nditer(arr):
#   print(x)
  
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


for x in np.nditer(arr[1, ::2]):
  print(x)

5
7


In [47]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
arr = np.stack((arr2,arr1),axis=0)
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])
new = np.array_split(arr, 99)
print(new)


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)
print(newarr[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32),

In [56]:

x=np.random.randint(100, size=(5,2))

print(x)

[[75 85]
 [53 27]
 [56 25]
 [17 92]
 [20 41]]


In [63]:
print(np.zeros((13, 4)))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
